version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:1.10.0"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "$PWD:/etc/selenoid/:ro" # assumed current dir contains browsers.json
      - "$PWD/video/:/opt/selenoid/video/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/video/
  selenoid-ui:
    image: "aerokube/selenoid-ui:1.9.1"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
